name: InPe
author: WeMake
markdown: kramdown
baseurl:
permalink: blog/:year/:month/:day/:title/
plugins:
  - jekyll-sitemap
  # - jekyll-paginate
# paginate: 10
# paginate_path: /blog/page:num/
exclude: [README.md]
github: [metadata]

title: "InPe by opencarecc"
tagline: "an open source wearable device that can detect fall and call for emergency"

# multilingual stuff
index:
  en:
  it: it/index.html

default_lang: "en"

# Facebook OpenGraph stuff
opengraph:
  title: "InPe by opencarecc"
  url: "http://inpe.opencare.cc"
  description: "an open source wearable device that can detect fall and call for emergency"
  image_url: "http://opencarecc.github.io/inpe/assets/OC-Logo-socials.png"

# Twitter Card stuff
twitter:
  site: "InPe by opencarecc"
  title: "InPe by opencarecc"
  description: "an open source wearable device that can detect fall and call for emergency"
  creator: "opencarecc"
  domain: "http://inpe.opencare.cc"
  image_url: "http://opencarecc.github.io/inpe/assets/OC-Logo-socials.png"
